name: Greetings
description: A greeting to someone
inputs:
  name:
    required: true
outputs:
  success:
    value: ${{ steps.id.outputs.success }}
runs:
  using: "composite"
  steps:
    - name: hello
      shell: bash
      run: echo "Hello ${{ inputs.name }}!"
    - name: return code
      id: return
      shell: bash
      run: echo "success=1" >> $GITHUB_OUTPUT

